//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalExaminationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalExams
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ExamDate { get; set; }
        public int ResultId { get; set; }
        public string DoctorName { get; set; }
        public string DoctorPosition { get; set; }
        public bool IsPassed { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ExamResults ExamResults { get; set; }
    }
}
