//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MED
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_history
    {
        public int history_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public int stavka { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual employees employees { get; set; }
        public virtual positions positions { get; set; }
    }
}
