//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MED
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization
    {
        public int organization_id { get; set; }
        public string name { get; set; }
        public string short_name { get; set; }
        public string address { get; set; }
    }
}
