//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepairMMEntities : DbContext
    {
        private static RepairMMEntities _context;
        public RepairMMEntities()
            : base("name=RepairMMEntities")
        {
        }

        public static RepairMMEntities GetConetxt()
        {
            if(_context == null)
                _context = new RepairMMEntities();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyUsers> CompanyUsers { get; set; }
        public virtual DbSet<Individual> Individual { get; set; }
        public virtual DbSet<Legal> Legal { get; set; }
        public virtual DbSet<NumberComm> NumberComm { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<RepeirCause> RepeirCause { get; set; }
        public virtual DbSet<ViewComm> ViewComm { get; set; }
    }
}
