//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int Receipt_Id { get; set; }
        public Nullable<System.DateTime> Receipt_Date { get; set; }
        public Nullable<System.DateTime> Receipt_RepeirDate { get; set; }
        public Nullable<System.DateTime> Receipt_EndRepeirDate { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> CompanyUsers_Id { get; set; }
        public Nullable<int> RepeirCause_Id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyUsers CompanyUsers { get; set; }
        public virtual RepeirCause RepeirCause { get; set; }
    }
}
