//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breakdown
    {
        public int Id { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FailureReason { get; set; }
        public string ReturnMethod { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
