//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagnostick
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostics
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public System.DateTime MeasureDateTime { get; set; }
        public string ParameterName { get; set; }
        public double Value { get; set; }
        public string Unit { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeePosition { get; set; }
        public string Department { get; set; }
        public string ExternalOrganizationName { get; set; }
        public string ExternalOrganizationAddress { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
