//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagnostick
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiagnostikaDeviceEntities : DbContext
    {
        private static DiagnostikaDeviceEntities _context;
        public DiagnostikaDeviceEntities()
            : base("name=DiagnostikaDeviceEntities")
        {
        }

        public static DiagnostikaDeviceEntities GetContext()
        {
            if(_context == null) 
                _context = new DiagnostikaDeviceEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnostics> Diagnostics { get; set; }
        public virtual DbSet<Enterprises> Enterprises { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentAssignments> EquipmentAssignments { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
