//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagnostick
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAssignments
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public int SiteId { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime AssignmentDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Sites Sites { get; set; }
    }
}
