//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestBaseProbaEntities : DbContext
    {
        private static TestBaseProbaEntities _context;

        public TestBaseProbaEntities()
            : base("name=TestBaseProbaEntities")
        {
        }

        public static TestBaseProbaEntities GetContext() 
        {
            if(_context == null)
                _context = new TestBaseProbaEntities();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Tech> Tech { get; set; }
        public virtual DbSet<TypeTech> TypeTech { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
