//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ReqID { get; set; }
        public string ReqName { get; set; }
        public Nullable<int> ReqNumber { get; set; }
        public Nullable<int> TechID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateStop { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Tech Tech { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
