//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tech
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tech()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int TechID { get; set; }
        public string TechName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> InventNumber { get; set; }
        public Nullable<int> PriceTech { get; set; }
        public Nullable<System.DateTime> DateBuyTech { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual TypeTech TypeTech { get; set; }
    }
}
