//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeTech
    {
        public int TypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual Tech Tech { get; set; }
    }
}
